### ISSUE TITLE
Australia Sydney and Melb DC's will be live 2014-10-27

### ISSUE THREAD

**Issue by mehmet-ozdemir** [nzbart/AzureSitePing#4]
Azure DC's in Sydney and Melbourne will be live next week as per:

http://www.lifehacker.com.au/2014/10/microsofts-australian-azure-data-centres-will-open-next-week/

Will you be able to add support for these two as well?

**Comment by nzbart** [comment]
No problem. I'll set it up as soon as I can after it goes live.

**Comment by nzbart** [comment]
I've added the new DCs. Thanks for reminding me!
